export { default as Hero } from './Hero.svelte'
export { default as Services } from './Services.svelte'
export { default as Black } from './Black.svelte'
export { default as About } from './About.svelte'
export { default as Projects } from './Projects.svelte'
export { default as Contact } from './Contact.svelte'
